#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace X.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="x.xue")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertx_answer(x_answer instance);
    partial void Updatex_answer(x_answer instance);
    partial void Deletex_answer(x_answer instance);
    partial void Insertx_dict(x_dict instance);
    partial void Updatex_dict(x_dict instance);
    partial void Deletex_dict(x_dict instance);
    partial void Insertx_mgr(x_mgr instance);
    partial void Updatex_mgr(x_mgr instance);
    partial void Deletex_mgr(x_mgr instance);
    partial void Insertx_question(x_question instance);
    partial void Updatex_question(x_question instance);
    partial void Deletex_question(x_question instance);
    partial void Insertx_user(x_user instance);
    partial void Updatex_user(x_user instance);
    partial void Deletex_user(x_user instance);
    partial void Insertx_order(x_order instance);
    partial void Updatex_order(x_order instance);
    partial void Deletex_order(x_order instance);
    partial void Insertx_paper(x_paper instance);
    partial void Updatex_paper(x_paper instance);
    partial void Deletex_paper(x_paper instance);
    partial void Insertx_down(x_down instance);
    partial void Updatex_down(x_down instance);
    partial void Deletex_down(x_down instance);
    partial void Insertx_fav(x_fav instance);
    partial void Updatex_fav(x_fav instance);
    partial void Deletex_fav(x_fav instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::X.Data.Properties.Settings.Default.x_xueConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<x_answer> x_answer
		{
			get
			{
				return this.GetTable<x_answer>();
			}
		}
		
		public System.Data.Linq.Table<x_dict> x_dict
		{
			get
			{
				return this.GetTable<x_dict>();
			}
		}
		
		public System.Data.Linq.Table<x_mgr> x_mgr
		{
			get
			{
				return this.GetTable<x_mgr>();
			}
		}
		
		public System.Data.Linq.Table<x_question> x_question
		{
			get
			{
				return this.GetTable<x_question>();
			}
		}
		
		public System.Data.Linq.Table<x_user> x_user
		{
			get
			{
				return this.GetTable<x_user>();
			}
		}
		
		public System.Data.Linq.Table<x_order> x_order
		{
			get
			{
				return this.GetTable<x_order>();
			}
		}
		
		public System.Data.Linq.Table<x_paper> x_paper
		{
			get
			{
				return this.GetTable<x_paper>();
			}
		}
		
		public System.Data.Linq.Table<x_down> x_down
		{
			get
			{
				return this.GetTable<x_down>();
			}
		}
		
		public System.Data.Linq.Table<x_fav> x_fav
		{
			get
			{
				return this.GetTable<x_fav>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.x_answer")]
	public partial class x_answer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _answer_id;
		
		private System.Nullable<long> _question_id;
		
		private string _no;
		
		private string _result;
		
		private string _remark;
		
		private EntityRef<x_question> _x_question;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onanswer_idChanging(long value);
    partial void Onanswer_idChanged();
    partial void Onquestion_idChanging(System.Nullable<long> value);
    partial void Onquestion_idChanged();
    partial void OnnoChanging(string value);
    partial void OnnoChanged();
    partial void OnresultChanging(string value);
    partial void OnresultChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    #endregion
		
		public x_answer()
		{
			this._x_question = default(EntityRef<x_question>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long answer_id
		{
			get
			{
				return this._answer_id;
			}
			set
			{
				if ((this._answer_id != value))
				{
					this.Onanswer_idChanging(value);
					this.SendPropertyChanging();
					this._answer_id = value;
					this.SendPropertyChanged("answer_id");
					this.Onanswer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_id", DbType="BigInt")]
		public System.Nullable<long> question_id
		{
			get
			{
				return this._question_id;
			}
			set
			{
				if ((this._question_id != value))
				{
					if (this._x_question.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onquestion_idChanging(value);
					this.SendPropertyChanging();
					this._question_id = value;
					this.SendPropertyChanged("question_id");
					this.Onquestion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no", DbType="NVarChar(10)")]
		public string no
		{
			get
			{
				return this._no;
			}
			set
			{
				if ((this._no != value))
				{
					this.OnnoChanging(value);
					this.SendPropertyChanging();
					this._no = value;
					this.SendPropertyChanged("no");
					this.OnnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result", DbType="NVarChar(100)")]
		public string result
		{
			get
			{
				return this._result;
			}
			set
			{
				if ((this._result != value))
				{
					this.OnresultChanging(value);
					this.SendPropertyChanging();
					this._result = value;
					this.SendPropertyChanged("result");
					this.OnresultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="x_question_x_answer", Storage="_x_question", ThisKey="question_id", OtherKey="question_id", IsForeignKey=true)]
		public x_question x_question
		{
			get
			{
				return this._x_question.Entity;
			}
			set
			{
				x_question previousValue = this._x_question.Entity;
				if (((previousValue != value) 
							|| (this._x_question.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._x_question.Entity = null;
						previousValue.x_answer.Remove(this);
					}
					this._x_question.Entity = value;
					if ((value != null))
					{
						value.x_answer.Add(this);
						this._question_id = value.question_id;
					}
					else
					{
						this._question_id = default(Nullable<long>);
					}
					this.SendPropertyChanged("x_question");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.x_dict")]
	public partial class x_dict : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _dict_id;
		
		private string _code;
		
		private string _img;
		
		private string _name;
		
		private string _jp;
		
		private string _upval;
		
		private string _value;
		
		private System.Nullable<int> _sort;
		
		private string _f1;
		
		private string _f2;
		
		private System.Nullable<int> _f3;
		
		private System.Nullable<int> _f4;
		
		private System.Nullable<int> _f5;
		
		private System.Nullable<int> _f6;
		
		private System.Nullable<int> _f7;
		
		private System.Nullable<int> _f8;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondict_idChanging(long value);
    partial void Ondict_idChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnjpChanging(string value);
    partial void OnjpChanged();
    partial void OnupvalChanging(string value);
    partial void OnupvalChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    partial void OnsortChanging(System.Nullable<int> value);
    partial void OnsortChanged();
    partial void Onf1Changing(string value);
    partial void Onf1Changed();
    partial void Onf2Changing(string value);
    partial void Onf2Changed();
    partial void Onf3Changing(System.Nullable<int> value);
    partial void Onf3Changed();
    partial void Onf4Changing(System.Nullable<int> value);
    partial void Onf4Changed();
    partial void Onf5Changing(System.Nullable<int> value);
    partial void Onf5Changed();
    partial void Onf6Changing(System.Nullable<int> value);
    partial void Onf6Changed();
    partial void Onf7Changing(System.Nullable<int> value);
    partial void Onf7Changed();
    partial void Onf8Changing(System.Nullable<int> value);
    partial void Onf8Changed();
    #endregion
		
		public x_dict()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dict_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long dict_id
		{
			get
			{
				return this._dict_id;
			}
			set
			{
				if ((this._dict_id != value))
				{
					this.Ondict_idChanging(value);
					this.SendPropertyChanging();
					this._dict_id = value;
					this.SendPropertyChanged("dict_id");
					this.Ondict_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NVarChar(20)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(200)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jp", DbType="NVarChar(50)")]
		public string jp
		{
			get
			{
				return this._jp;
			}
			set
			{
				if ((this._jp != value))
				{
					this.OnjpChanging(value);
					this.SendPropertyChanging();
					this._jp = value;
					this.SendPropertyChanged("jp");
					this.OnjpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upval", DbType="NVarChar(10)")]
		public string upval
		{
			get
			{
				return this._upval;
			}
			set
			{
				if ((this._upval != value))
				{
					this.OnupvalChanging(value);
					this.SendPropertyChanging();
					this._upval = value;
					this.SendPropertyChanged("upval");
					this.OnupvalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="NVarChar(100)")]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sort", DbType="Int")]
		public System.Nullable<int> sort
		{
			get
			{
				return this._sort;
			}
			set
			{
				if ((this._sort != value))
				{
					this.OnsortChanging(value);
					this.SendPropertyChanging();
					this._sort = value;
					this.SendPropertyChanged("sort");
					this.OnsortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f1", DbType="NVarChar(200)")]
		public string f1
		{
			get
			{
				return this._f1;
			}
			set
			{
				if ((this._f1 != value))
				{
					this.Onf1Changing(value);
					this.SendPropertyChanging();
					this._f1 = value;
					this.SendPropertyChanged("f1");
					this.Onf1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f2", DbType="NVarChar(200)")]
		public string f2
		{
			get
			{
				return this._f2;
			}
			set
			{
				if ((this._f2 != value))
				{
					this.Onf2Changing(value);
					this.SendPropertyChanging();
					this._f2 = value;
					this.SendPropertyChanged("f2");
					this.Onf2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f3", DbType="Int")]
		public System.Nullable<int> f3
		{
			get
			{
				return this._f3;
			}
			set
			{
				if ((this._f3 != value))
				{
					this.Onf3Changing(value);
					this.SendPropertyChanging();
					this._f3 = value;
					this.SendPropertyChanged("f3");
					this.Onf3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f4", DbType="Int")]
		public System.Nullable<int> f4
		{
			get
			{
				return this._f4;
			}
			set
			{
				if ((this._f4 != value))
				{
					this.Onf4Changing(value);
					this.SendPropertyChanging();
					this._f4 = value;
					this.SendPropertyChanged("f4");
					this.Onf4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f5", DbType="Int")]
		public System.Nullable<int> f5
		{
			get
			{
				return this._f5;
			}
			set
			{
				if ((this._f5 != value))
				{
					this.Onf5Changing(value);
					this.SendPropertyChanging();
					this._f5 = value;
					this.SendPropertyChanged("f5");
					this.Onf5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f6", DbType="Int")]
		public System.Nullable<int> f6
		{
			get
			{
				return this._f6;
			}
			set
			{
				if ((this._f6 != value))
				{
					this.Onf6Changing(value);
					this.SendPropertyChanging();
					this._f6 = value;
					this.SendPropertyChanged("f6");
					this.Onf6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f7", DbType="Int")]
		public System.Nullable<int> f7
		{
			get
			{
				return this._f7;
			}
			set
			{
				if ((this._f7 != value))
				{
					this.Onf7Changing(value);
					this.SendPropertyChanging();
					this._f7 = value;
					this.SendPropertyChanged("f7");
					this.Onf7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f8", DbType="Int")]
		public System.Nullable<int> f8
		{
			get
			{
				return this._f8;
			}
			set
			{
				if ((this._f8 != value))
				{
					this.Onf8Changing(value);
					this.SendPropertyChanging();
					this._f8 = value;
					this.SendPropertyChanged("f8");
					this.Onf8Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.x_mgr")]
	public partial class x_mgr : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _mgr_id;
		
		private string _uin;
		
		private string _pwd;
		
		private string _name;
		
		private string _email;
		
		private string _tel;
		
		private string _job;
		
		private string _remark;
		
		private System.Nullable<System.DateTime> _ctime;
		
		private string _ukey;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmgr_idChanging(long value);
    partial void Onmgr_idChanged();
    partial void OnuinChanging(string value);
    partial void OnuinChanged();
    partial void OnpwdChanging(string value);
    partial void OnpwdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OnjobChanging(string value);
    partial void OnjobChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void OnctimeChanging(System.Nullable<System.DateTime> value);
    partial void OnctimeChanged();
    partial void OnukeyChanging(string value);
    partial void OnukeyChanged();
    #endregion
		
		public x_mgr()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mgr_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long mgr_id
		{
			get
			{
				return this._mgr_id;
			}
			set
			{
				if ((this._mgr_id != value))
				{
					this.Onmgr_idChanging(value);
					this.SendPropertyChanging();
					this._mgr_id = value;
					this.SendPropertyChanged("mgr_id");
					this.Onmgr_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uin", DbType="NVarChar(64)")]
		public string uin
		{
			get
			{
				return this._uin;
			}
			set
			{
				if ((this._uin != value))
				{
					this.OnuinChanging(value);
					this.SendPropertyChanging();
					this._uin = value;
					this.SendPropertyChanged("uin");
					this.OnuinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="NVarChar(64)")]
		public string pwd
		{
			get
			{
				return this._pwd;
			}
			set
			{
				if ((this._pwd != value))
				{
					this.OnpwdChanging(value);
					this.SendPropertyChanging();
					this._pwd = value;
					this.SendPropertyChanged("pwd");
					this.OnpwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(20)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="NVarChar(12)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job", DbType="NVarChar(40)")]
		public string job
		{
			get
			{
				return this._job;
			}
			set
			{
				if ((this._job != value))
				{
					this.OnjobChanging(value);
					this.SendPropertyChanging();
					this._job = value;
					this.SendPropertyChanged("job");
					this.OnjobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="NVarChar(400)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ctime
		{
			get
			{
				return this._ctime;
			}
			set
			{
				if ((this._ctime != value))
				{
					this.OnctimeChanging(value);
					this.SendPropertyChanging();
					this._ctime = value;
					this.SendPropertyChanged("ctime");
					this.OnctimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ukey", DbType="NVarChar(64)")]
		public string ukey
		{
			get
			{
				return this._ukey;
			}
			set
			{
				if ((this._ukey != value))
				{
					this.OnukeyChanging(value);
					this.SendPropertyChanging();
					this._ukey = value;
					this.SendPropertyChanged("ukey");
					this.OnukeyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.x_question")]
	public partial class x_question : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _question_id;
		
		private System.Nullable<int> _subject;
		
		private System.Nullable<int> _book;
		
		private System.Nullable<int> _chapter;
		
		private System.Nullable<int> _topic;
		
		private System.Nullable<int> _type;
		
		private System.Nullable<int> _easy;
		
		private string _knowledge;
		
		private System.Nullable<int> _knowledgecount;
		
		private string _title;
		
		private System.Nullable<int> _score;
		
		private System.Nullable<System.DateTime> _ctime;
		
		private string _src;
		
		private System.Nullable<System.DateTime> _mtime;
		
		private System.Nullable<int> _hits;
		
		private EntitySet<x_answer> _x_answer;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onquestion_idChanging(long value);
    partial void Onquestion_idChanged();
    partial void OnsubjectChanging(System.Nullable<int> value);
    partial void OnsubjectChanged();
    partial void OnbookChanging(System.Nullable<int> value);
    partial void OnbookChanged();
    partial void OnchapterChanging(System.Nullable<int> value);
    partial void OnchapterChanged();
    partial void OntopicChanging(System.Nullable<int> value);
    partial void OntopicChanged();
    partial void OntypeChanging(System.Nullable<int> value);
    partial void OntypeChanged();
    partial void OneasyChanging(System.Nullable<int> value);
    partial void OneasyChanged();
    partial void OnknowledgeChanging(string value);
    partial void OnknowledgeChanged();
    partial void OnknowledgecountChanging(System.Nullable<int> value);
    partial void OnknowledgecountChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnscoreChanging(System.Nullable<int> value);
    partial void OnscoreChanged();
    partial void OnctimeChanging(System.Nullable<System.DateTime> value);
    partial void OnctimeChanged();
    partial void OnsrcChanging(string value);
    partial void OnsrcChanged();
    partial void OnmtimeChanging(System.Nullable<System.DateTime> value);
    partial void OnmtimeChanged();
    partial void OnhitsChanging(System.Nullable<int> value);
    partial void OnhitsChanged();
    #endregion
		
		public x_question()
		{
			this._x_answer = new EntitySet<x_answer>(new Action<x_answer>(this.attach_x_answer), new Action<x_answer>(this.detach_x_answer));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long question_id
		{
			get
			{
				return this._question_id;
			}
			set
			{
				if ((this._question_id != value))
				{
					this.Onquestion_idChanging(value);
					this.SendPropertyChanging();
					this._question_id = value;
					this.SendPropertyChanged("question_id");
					this.Onquestion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="Int")]
		public System.Nullable<int> subject
		{
			get
			{
				return this._subject;
			}
			set
			{
				if ((this._subject != value))
				{
					this.OnsubjectChanging(value);
					this.SendPropertyChanging();
					this._subject = value;
					this.SendPropertyChanged("subject");
					this.OnsubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book", DbType="Int")]
		public System.Nullable<int> book
		{
			get
			{
				return this._book;
			}
			set
			{
				if ((this._book != value))
				{
					this.OnbookChanging(value);
					this.SendPropertyChanging();
					this._book = value;
					this.SendPropertyChanged("book");
					this.OnbookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chapter", DbType="Int")]
		public System.Nullable<int> chapter
		{
			get
			{
				return this._chapter;
			}
			set
			{
				if ((this._chapter != value))
				{
					this.OnchapterChanging(value);
					this.SendPropertyChanging();
					this._chapter = value;
					this.SendPropertyChanged("chapter");
					this.OnchapterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic", DbType="Int")]
		public System.Nullable<int> topic
		{
			get
			{
				return this._topic;
			}
			set
			{
				if ((this._topic != value))
				{
					this.OntopicChanging(value);
					this.SendPropertyChanging();
					this._topic = value;
					this.SendPropertyChanged("topic");
					this.OntopicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_easy", DbType="Int")]
		public System.Nullable<int> easy
		{
			get
			{
				return this._easy;
			}
			set
			{
				if ((this._easy != value))
				{
					this.OneasyChanging(value);
					this.SendPropertyChanging();
					this._easy = value;
					this.SendPropertyChanged("easy");
					this.OneasyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_knowledge", DbType="NVarChar(800)")]
		public string knowledge
		{
			get
			{
				return this._knowledge;
			}
			set
			{
				if ((this._knowledge != value))
				{
					this.OnknowledgeChanging(value);
					this.SendPropertyChanging();
					this._knowledge = value;
					this.SendPropertyChanged("knowledge");
					this.OnknowledgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_knowledgecount", DbType="Int")]
		public System.Nullable<int> knowledgecount
		{
			get
			{
				return this._knowledgecount;
			}
			set
			{
				if ((this._knowledgecount != value))
				{
					this.OnknowledgecountChanging(value);
					this.SendPropertyChanging();
					this._knowledgecount = value;
					this.SendPropertyChanged("knowledgecount");
					this.OnknowledgecountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_score", DbType="Int")]
		public System.Nullable<int> score
		{
			get
			{
				return this._score;
			}
			set
			{
				if ((this._score != value))
				{
					this.OnscoreChanging(value);
					this.SendPropertyChanging();
					this._score = value;
					this.SendPropertyChanged("score");
					this.OnscoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ctime
		{
			get
			{
				return this._ctime;
			}
			set
			{
				if ((this._ctime != value))
				{
					this.OnctimeChanging(value);
					this.SendPropertyChanging();
					this._ctime = value;
					this.SendPropertyChanged("ctime");
					this.OnctimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_src", DbType="NVarChar(200)")]
		public string src
		{
			get
			{
				return this._src;
			}
			set
			{
				if ((this._src != value))
				{
					this.OnsrcChanging(value);
					this.SendPropertyChanging();
					this._src = value;
					this.SendPropertyChanged("src");
					this.OnsrcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> mtime
		{
			get
			{
				return this._mtime;
			}
			set
			{
				if ((this._mtime != value))
				{
					this.OnmtimeChanging(value);
					this.SendPropertyChanging();
					this._mtime = value;
					this.SendPropertyChanged("mtime");
					this.OnmtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hits", DbType="Int")]
		public System.Nullable<int> hits
		{
			get
			{
				return this._hits;
			}
			set
			{
				if ((this._hits != value))
				{
					this.OnhitsChanging(value);
					this.SendPropertyChanging();
					this._hits = value;
					this.SendPropertyChanged("hits");
					this.OnhitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="x_question_x_answer", Storage="_x_answer", ThisKey="question_id", OtherKey="question_id")]
		public EntitySet<x_answer> x_answer
		{
			get
			{
				return this._x_answer;
			}
			set
			{
				this._x_answer.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_x_answer(x_answer entity)
		{
			this.SendPropertyChanging();
			entity.x_question = this;
		}
		
		private void detach_x_answer(x_answer entity)
		{
			this.SendPropertyChanging();
			entity.x_question = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.x_user")]
	public partial class x_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _user_id;
		
		private string _headimg;
		
		private string _uid;
		
		private string _name;
		
		private string _school;
		
		private string _tel;
		
		private System.Nullable<decimal> _balance;
		
		private System.Nullable<System.DateTime> _ctime;
		
		private System.Nullable<System.DateTime> _etime;
		
		private string _ukey;
		
		private EntitySet<x_order> _x_order;
		
		private EntitySet<x_down> _x_down;
		
		private EntitySet<x_fav> _x_fav;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(long value);
    partial void Onuser_idChanged();
    partial void OnheadimgChanging(string value);
    partial void OnheadimgChanged();
    partial void OnuidChanging(string value);
    partial void OnuidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnschoolChanging(string value);
    partial void OnschoolChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OnbalanceChanging(System.Nullable<decimal> value);
    partial void OnbalanceChanged();
    partial void OnctimeChanging(System.Nullable<System.DateTime> value);
    partial void OnctimeChanged();
    partial void OnetimeChanging(System.Nullable<System.DateTime> value);
    partial void OnetimeChanged();
    partial void OnukeyChanging(string value);
    partial void OnukeyChanged();
    #endregion
		
		public x_user()
		{
			this._x_order = new EntitySet<x_order>(new Action<x_order>(this.attach_x_order), new Action<x_order>(this.detach_x_order));
			this._x_down = new EntitySet<x_down>(new Action<x_down>(this.attach_x_down), new Action<x_down>(this.detach_x_down));
			this._x_fav = new EntitySet<x_fav>(new Action<x_fav>(this.attach_x_fav), new Action<x_fav>(this.detach_x_fav));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_headimg", DbType="NVarChar(200)")]
		public string headimg
		{
			get
			{
				return this._headimg;
			}
			set
			{
				if ((this._headimg != value))
				{
					this.OnheadimgChanging(value);
					this.SendPropertyChanging();
					this._headimg = value;
					this.SendPropertyChanged("headimg");
					this.OnheadimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="NVarChar(64)")]
		public string uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_school", DbType="NVarChar(60)")]
		public string school
		{
			get
			{
				return this._school;
			}
			set
			{
				if ((this._school != value))
				{
					this.OnschoolChanging(value);
					this.SendPropertyChanging();
					this._school = value;
					this.SendPropertyChanged("school");
					this.OnschoolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="NVarChar(11)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> balance
		{
			get
			{
				return this._balance;
			}
			set
			{
				if ((this._balance != value))
				{
					this.OnbalanceChanging(value);
					this.SendPropertyChanging();
					this._balance = value;
					this.SendPropertyChanged("balance");
					this.OnbalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ctime
		{
			get
			{
				return this._ctime;
			}
			set
			{
				if ((this._ctime != value))
				{
					this.OnctimeChanging(value);
					this.SendPropertyChanging();
					this._ctime = value;
					this.SendPropertyChanged("ctime");
					this.OnctimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etime", DbType="DateTime")]
		public System.Nullable<System.DateTime> etime
		{
			get
			{
				return this._etime;
			}
			set
			{
				if ((this._etime != value))
				{
					this.OnetimeChanging(value);
					this.SendPropertyChanging();
					this._etime = value;
					this.SendPropertyChanged("etime");
					this.OnetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ukey", DbType="NVarChar(64)")]
		public string ukey
		{
			get
			{
				return this._ukey;
			}
			set
			{
				if ((this._ukey != value))
				{
					this.OnukeyChanging(value);
					this.SendPropertyChanging();
					this._ukey = value;
					this.SendPropertyChanged("ukey");
					this.OnukeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="x_user_x_order", Storage="_x_order", ThisKey="user_id", OtherKey="user_id")]
		public EntitySet<x_order> x_order
		{
			get
			{
				return this._x_order;
			}
			set
			{
				this._x_order.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="x_user_x_down", Storage="_x_down", ThisKey="user_id", OtherKey="user_id")]
		public EntitySet<x_down> x_down
		{
			get
			{
				return this._x_down;
			}
			set
			{
				this._x_down.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="x_user_x_fav", Storage="_x_fav", ThisKey="user_id", OtherKey="user_id")]
		public EntitySet<x_fav> x_fav
		{
			get
			{
				return this._x_fav;
			}
			set
			{
				this._x_fav.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_x_order(x_order entity)
		{
			this.SendPropertyChanging();
			entity.x_user = this;
		}
		
		private void detach_x_order(x_order entity)
		{
			this.SendPropertyChanging();
			entity.x_user = null;
		}
		
		private void attach_x_down(x_down entity)
		{
			this.SendPropertyChanging();
			entity.x_user = this;
		}
		
		private void detach_x_down(x_down entity)
		{
			this.SendPropertyChanging();
			entity.x_user = null;
		}
		
		private void attach_x_fav(x_fav entity)
		{
			this.SendPropertyChanging();
			entity.x_user = this;
		}
		
		private void detach_x_fav(x_fav entity)
		{
			this.SendPropertyChanging();
			entity.x_user = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.x_order")]
	public partial class x_order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _order_id;
		
		private System.Nullable<long> _user_id;
		
		private System.Nullable<System.DateTime> _etime;
		
		private System.Nullable<long> _pid;
		
		private string _desc;
		
		private System.Nullable<decimal> _amount;
		
		private string _no;
		
		private string _app_no;
		
		private System.Nullable<int> _platform;
		
		private System.Nullable<System.DateTime> _ctime;
		
		private System.Nullable<int> _status;
		
		private string _err_msg;
		
		private System.Nullable<bool> _user_del;
		
		private EntityRef<x_user> _x_user;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onorder_idChanging(long value);
    partial void Onorder_idChanged();
    partial void Onuser_idChanging(System.Nullable<long> value);
    partial void Onuser_idChanged();
    partial void OnetimeChanging(System.Nullable<System.DateTime> value);
    partial void OnetimeChanged();
    partial void OnpidChanging(System.Nullable<long> value);
    partial void OnpidChanged();
    partial void OndescChanging(string value);
    partial void OndescChanged();
    partial void OnamountChanging(System.Nullable<decimal> value);
    partial void OnamountChanged();
    partial void OnnoChanging(string value);
    partial void OnnoChanged();
    partial void Onapp_noChanging(string value);
    partial void Onapp_noChanged();
    partial void OnplatformChanging(System.Nullable<int> value);
    partial void OnplatformChanged();
    partial void OnctimeChanging(System.Nullable<System.DateTime> value);
    partial void OnctimeChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void Onerr_msgChanging(string value);
    partial void Onerr_msgChanged();
    partial void Onuser_delChanging(System.Nullable<bool> value);
    partial void Onuser_delChanged();
    #endregion
		
		public x_order()
		{
			this._x_user = default(EntityRef<x_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this.Onorder_idChanging(value);
					this.SendPropertyChanging();
					this._order_id = value;
					this.SendPropertyChanged("order_id");
					this.Onorder_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="BigInt")]
		public System.Nullable<long> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._x_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etime", DbType="DateTime")]
		public System.Nullable<System.DateTime> etime
		{
			get
			{
				return this._etime;
			}
			set
			{
				if ((this._etime != value))
				{
					this.OnetimeChanging(value);
					this.SendPropertyChanging();
					this._etime = value;
					this.SendPropertyChanged("etime");
					this.OnetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", DbType="BigInt")]
		public System.Nullable<long> pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this.OnpidChanging(value);
					this.SendPropertyChanging();
					this._pid = value;
					this.SendPropertyChanged("pid");
					this.OnpidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[desc]", Storage="_desc", DbType="NVarChar(400)")]
		public string desc
		{
			get
			{
				return this._desc;
			}
			set
			{
				if ((this._desc != value))
				{
					this.OndescChanging(value);
					this.SendPropertyChanging();
					this._desc = value;
					this.SendPropertyChanged("desc");
					this.OndescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if ((this._amount != value))
				{
					this.OnamountChanging(value);
					this.SendPropertyChanging();
					this._amount = value;
					this.SendPropertyChanged("amount");
					this.OnamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no", DbType="NVarChar(64)")]
		public string no
		{
			get
			{
				return this._no;
			}
			set
			{
				if ((this._no != value))
				{
					this.OnnoChanging(value);
					this.SendPropertyChanging();
					this._no = value;
					this.SendPropertyChanged("no");
					this.OnnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_app_no", DbType="NVarChar(64)")]
		public string app_no
		{
			get
			{
				return this._app_no;
			}
			set
			{
				if ((this._app_no != value))
				{
					this.Onapp_noChanging(value);
					this.SendPropertyChanging();
					this._app_no = value;
					this.SendPropertyChanged("app_no");
					this.Onapp_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_platform", DbType="Int")]
		public System.Nullable<int> platform
		{
			get
			{
				return this._platform;
			}
			set
			{
				if ((this._platform != value))
				{
					this.OnplatformChanging(value);
					this.SendPropertyChanging();
					this._platform = value;
					this.SendPropertyChanged("platform");
					this.OnplatformChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ctime
		{
			get
			{
				return this._ctime;
			}
			set
			{
				if ((this._ctime != value))
				{
					this.OnctimeChanging(value);
					this.SendPropertyChanging();
					this._ctime = value;
					this.SendPropertyChanged("ctime");
					this.OnctimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_err_msg", DbType="NVarChar(400)")]
		public string err_msg
		{
			get
			{
				return this._err_msg;
			}
			set
			{
				if ((this._err_msg != value))
				{
					this.Onerr_msgChanging(value);
					this.SendPropertyChanging();
					this._err_msg = value;
					this.SendPropertyChanged("err_msg");
					this.Onerr_msgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_del", DbType="Bit")]
		public System.Nullable<bool> user_del
		{
			get
			{
				return this._user_del;
			}
			set
			{
				if ((this._user_del != value))
				{
					this.Onuser_delChanging(value);
					this.SendPropertyChanging();
					this._user_del = value;
					this.SendPropertyChanged("user_del");
					this.Onuser_delChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="x_user_x_order", Storage="_x_user", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
		public x_user x_user
		{
			get
			{
				return this._x_user.Entity;
			}
			set
			{
				x_user previousValue = this._x_user.Entity;
				if (((previousValue != value) 
							|| (this._x_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._x_user.Entity = null;
						previousValue.x_order.Remove(this);
					}
					this._x_user.Entity = value;
					if ((value != null))
					{
						value.x_order.Add(this);
						this._user_id = value.user_id;
					}
					else
					{
						this._user_id = default(Nullable<long>);
					}
					this.SendPropertyChanged("x_user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.x_paper")]
	public partial class x_paper : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _paper_id;
		
		private System.Nullable<long> _user_id;
		
		private System.Nullable<int> _subject;
		
		private System.Nullable<int> _book;
		
		private System.Nullable<int> _type;
		
		private System.Nullable<int> _area;
		
		private string _group;
		
		private string _topic;
		
		private string _qids;
		
		private string _setting;
		
		private System.Nullable<int> _score;
		
		private System.Nullable<int> _qcount;
		
		private System.Nullable<decimal> _price;
		
		private System.Nullable<System.DateTime> _ctime;
		
		private System.Nullable<System.DateTime> _mtime;
		
		private EntitySet<x_down> _x_down;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpaper_idChanging(long value);
    partial void Onpaper_idChanged();
    partial void Onuser_idChanging(System.Nullable<long> value);
    partial void Onuser_idChanged();
    partial void OnsubjectChanging(System.Nullable<int> value);
    partial void OnsubjectChanged();
    partial void OnbookChanging(System.Nullable<int> value);
    partial void OnbookChanged();
    partial void OntypeChanging(System.Nullable<int> value);
    partial void OntypeChanged();
    partial void OnareaChanging(System.Nullable<int> value);
    partial void OnareaChanged();
    partial void OngroupChanging(string value);
    partial void OngroupChanged();
    partial void OntopicChanging(string value);
    partial void OntopicChanged();
    partial void OnqidsChanging(string value);
    partial void OnqidsChanged();
    partial void OnsettingChanging(string value);
    partial void OnsettingChanged();
    partial void OnscoreChanging(System.Nullable<int> value);
    partial void OnscoreChanged();
    partial void OnqcountChanging(System.Nullable<int> value);
    partial void OnqcountChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void OnctimeChanging(System.Nullable<System.DateTime> value);
    partial void OnctimeChanged();
    partial void OnmtimeChanging(System.Nullable<System.DateTime> value);
    partial void OnmtimeChanged();
    #endregion
		
		public x_paper()
		{
			this._x_down = new EntitySet<x_down>(new Action<x_down>(this.attach_x_down), new Action<x_down>(this.detach_x_down));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paper_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long paper_id
		{
			get
			{
				return this._paper_id;
			}
			set
			{
				if ((this._paper_id != value))
				{
					this.Onpaper_idChanging(value);
					this.SendPropertyChanging();
					this._paper_id = value;
					this.SendPropertyChanged("paper_id");
					this.Onpaper_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="BigInt")]
		public System.Nullable<long> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="Int")]
		public System.Nullable<int> subject
		{
			get
			{
				return this._subject;
			}
			set
			{
				if ((this._subject != value))
				{
					this.OnsubjectChanging(value);
					this.SendPropertyChanging();
					this._subject = value;
					this.SendPropertyChanged("subject");
					this.OnsubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book", DbType="Int")]
		public System.Nullable<int> book
		{
			get
			{
				return this._book;
			}
			set
			{
				if ((this._book != value))
				{
					this.OnbookChanging(value);
					this.SendPropertyChanging();
					this._book = value;
					this.SendPropertyChanged("book");
					this.OnbookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="Int")]
		public System.Nullable<int> area
		{
			get
			{
				return this._area;
			}
			set
			{
				if ((this._area != value))
				{
					this.OnareaChanging(value);
					this.SendPropertyChanging();
					this._area = value;
					this.SendPropertyChanged("area");
					this.OnareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[group]", Storage="_group", DbType="NVarChar(250)")]
		public string group
		{
			get
			{
				return this._group;
			}
			set
			{
				if ((this._group != value))
				{
					this.OngroupChanging(value);
					this.SendPropertyChanging();
					this._group = value;
					this.SendPropertyChanged("group");
					this.OngroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic", DbType="NVarChar(200)")]
		public string topic
		{
			get
			{
				return this._topic;
			}
			set
			{
				if ((this._topic != value))
				{
					this.OntopicChanging(value);
					this.SendPropertyChanging();
					this._topic = value;
					this.SendPropertyChanged("topic");
					this.OntopicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qids", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string qids
		{
			get
			{
				return this._qids;
			}
			set
			{
				if ((this._qids != value))
				{
					this.OnqidsChanging(value);
					this.SendPropertyChanging();
					this._qids = value;
					this.SendPropertyChanged("qids");
					this.OnqidsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_setting", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string setting
		{
			get
			{
				return this._setting;
			}
			set
			{
				if ((this._setting != value))
				{
					this.OnsettingChanging(value);
					this.SendPropertyChanging();
					this._setting = value;
					this.SendPropertyChanged("setting");
					this.OnsettingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_score", DbType="Int")]
		public System.Nullable<int> score
		{
			get
			{
				return this._score;
			}
			set
			{
				if ((this._score != value))
				{
					this.OnscoreChanging(value);
					this.SendPropertyChanging();
					this._score = value;
					this.SendPropertyChanged("score");
					this.OnscoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qcount", DbType="Int")]
		public System.Nullable<int> qcount
		{
			get
			{
				return this._qcount;
			}
			set
			{
				if ((this._qcount != value))
				{
					this.OnqcountChanging(value);
					this.SendPropertyChanging();
					this._qcount = value;
					this.SendPropertyChanged("qcount");
					this.OnqcountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ctime
		{
			get
			{
				return this._ctime;
			}
			set
			{
				if ((this._ctime != value))
				{
					this.OnctimeChanging(value);
					this.SendPropertyChanging();
					this._ctime = value;
					this.SendPropertyChanged("ctime");
					this.OnctimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> mtime
		{
			get
			{
				return this._mtime;
			}
			set
			{
				if ((this._mtime != value))
				{
					this.OnmtimeChanging(value);
					this.SendPropertyChanging();
					this._mtime = value;
					this.SendPropertyChanged("mtime");
					this.OnmtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="x_paper_x_down", Storage="_x_down", ThisKey="paper_id", OtherKey="paper_id")]
		public EntitySet<x_down> x_down
		{
			get
			{
				return this._x_down;
			}
			set
			{
				this._x_down.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_x_down(x_down entity)
		{
			this.SendPropertyChanging();
			entity.x_paper = this;
		}
		
		private void detach_x_down(x_down entity)
		{
			this.SendPropertyChanging();
			entity.x_paper = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.x_down")]
	public partial class x_down : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _down_id;
		
		private System.Nullable<long> _user_id;
		
		private System.Nullable<long> _paper_id;
		
		private System.Nullable<int> _size;
		
		private System.Nullable<int> _type;
		
		private string _dkey;
		
		private System.Nullable<System.DateTime> _ctime;
		
		private EntityRef<x_paper> _x_paper;
		
		private EntityRef<x_user> _x_user;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondown_idChanging(long value);
    partial void Ondown_idChanged();
    partial void Onuser_idChanging(System.Nullable<long> value);
    partial void Onuser_idChanged();
    partial void Onpaper_idChanging(System.Nullable<long> value);
    partial void Onpaper_idChanged();
    partial void OnsizeChanging(System.Nullable<int> value);
    partial void OnsizeChanged();
    partial void OntypeChanging(System.Nullable<int> value);
    partial void OntypeChanged();
    partial void OndkeyChanging(string value);
    partial void OndkeyChanged();
    partial void OnctimeChanging(System.Nullable<System.DateTime> value);
    partial void OnctimeChanged();
    #endregion
		
		public x_down()
		{
			this._x_paper = default(EntityRef<x_paper>);
			this._x_user = default(EntityRef<x_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_down_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long down_id
		{
			get
			{
				return this._down_id;
			}
			set
			{
				if ((this._down_id != value))
				{
					this.Ondown_idChanging(value);
					this.SendPropertyChanging();
					this._down_id = value;
					this.SendPropertyChanged("down_id");
					this.Ondown_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="BigInt")]
		public System.Nullable<long> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._x_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paper_id", DbType="BigInt")]
		public System.Nullable<long> paper_id
		{
			get
			{
				return this._paper_id;
			}
			set
			{
				if ((this._paper_id != value))
				{
					if (this._x_paper.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpaper_idChanging(value);
					this.SendPropertyChanging();
					this._paper_id = value;
					this.SendPropertyChanged("paper_id");
					this.Onpaper_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="Int")]
		public System.Nullable<int> size
		{
			get
			{
				return this._size;
			}
			set
			{
				if ((this._size != value))
				{
					this.OnsizeChanging(value);
					this.SendPropertyChanging();
					this._size = value;
					this.SendPropertyChanged("size");
					this.OnsizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dkey", DbType="NVarChar(64)")]
		public string dkey
		{
			get
			{
				return this._dkey;
			}
			set
			{
				if ((this._dkey != value))
				{
					this.OndkeyChanging(value);
					this.SendPropertyChanging();
					this._dkey = value;
					this.SendPropertyChanged("dkey");
					this.OndkeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ctime
		{
			get
			{
				return this._ctime;
			}
			set
			{
				if ((this._ctime != value))
				{
					this.OnctimeChanging(value);
					this.SendPropertyChanging();
					this._ctime = value;
					this.SendPropertyChanged("ctime");
					this.OnctimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="x_paper_x_down", Storage="_x_paper", ThisKey="paper_id", OtherKey="paper_id", IsForeignKey=true)]
		public x_paper x_paper
		{
			get
			{
				return this._x_paper.Entity;
			}
			set
			{
				x_paper previousValue = this._x_paper.Entity;
				if (((previousValue != value) 
							|| (this._x_paper.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._x_paper.Entity = null;
						previousValue.x_down.Remove(this);
					}
					this._x_paper.Entity = value;
					if ((value != null))
					{
						value.x_down.Add(this);
						this._paper_id = value.paper_id;
					}
					else
					{
						this._paper_id = default(Nullable<long>);
					}
					this.SendPropertyChanged("x_paper");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="x_user_x_down", Storage="_x_user", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
		public x_user x_user
		{
			get
			{
				return this._x_user.Entity;
			}
			set
			{
				x_user previousValue = this._x_user.Entity;
				if (((previousValue != value) 
							|| (this._x_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._x_user.Entity = null;
						previousValue.x_down.Remove(this);
					}
					this._x_user.Entity = value;
					if ((value != null))
					{
						value.x_down.Add(this);
						this._user_id = value.user_id;
					}
					else
					{
						this._user_id = default(Nullable<long>);
					}
					this.SendPropertyChanged("x_user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.x_fav")]
	public partial class x_fav : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _fav_id;
		
		private System.Nullable<long> _user_id;
		
		private System.Nullable<int> _type;
		
		private System.Nullable<int> _group;
		
		private System.Nullable<int> _subject;
		
		private System.Nullable<long> _cid;
		
		private System.Nullable<System.DateTime> _ctime;
		
		private EntityRef<x_user> _x_user;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfav_idChanging(long value);
    partial void Onfav_idChanged();
    partial void Onuser_idChanging(System.Nullable<long> value);
    partial void Onuser_idChanged();
    partial void OntypeChanging(System.Nullable<int> value);
    partial void OntypeChanged();
    partial void OngroupChanging(System.Nullable<int> value);
    partial void OngroupChanged();
    partial void OnsubjectChanging(System.Nullable<int> value);
    partial void OnsubjectChanged();
    partial void OncidChanging(System.Nullable<long> value);
    partial void OncidChanged();
    partial void OnctimeChanging(System.Nullable<System.DateTime> value);
    partial void OnctimeChanged();
    #endregion
		
		public x_fav()
		{
			this._x_user = default(EntityRef<x_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fav_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long fav_id
		{
			get
			{
				return this._fav_id;
			}
			set
			{
				if ((this._fav_id != value))
				{
					this.Onfav_idChanging(value);
					this.SendPropertyChanging();
					this._fav_id = value;
					this.SendPropertyChanged("fav_id");
					this.Onfav_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="BigInt")]
		public System.Nullable<long> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._x_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[group]", Storage="_group", DbType="Int")]
		public System.Nullable<int> group
		{
			get
			{
				return this._group;
			}
			set
			{
				if ((this._group != value))
				{
					this.OngroupChanging(value);
					this.SendPropertyChanging();
					this._group = value;
					this.SendPropertyChanged("group");
					this.OngroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="Int")]
		public System.Nullable<int> subject
		{
			get
			{
				return this._subject;
			}
			set
			{
				if ((this._subject != value))
				{
					this.OnsubjectChanging(value);
					this.SendPropertyChanging();
					this._subject = value;
					this.SendPropertyChanged("subject");
					this.OnsubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid", DbType="BigInt")]
		public System.Nullable<long> cid
		{
			get
			{
				return this._cid;
			}
			set
			{
				if ((this._cid != value))
				{
					this.OncidChanging(value);
					this.SendPropertyChanging();
					this._cid = value;
					this.SendPropertyChanged("cid");
					this.OncidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ctime
		{
			get
			{
				return this._ctime;
			}
			set
			{
				if ((this._ctime != value))
				{
					this.OnctimeChanging(value);
					this.SendPropertyChanging();
					this._ctime = value;
					this.SendPropertyChanged("ctime");
					this.OnctimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="x_user_x_fav", Storage="_x_user", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
		public x_user x_user
		{
			get
			{
				return this._x_user.Entity;
			}
			set
			{
				x_user previousValue = this._x_user.Entity;
				if (((previousValue != value) 
							|| (this._x_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._x_user.Entity = null;
						previousValue.x_fav.Remove(this);
					}
					this._x_user.Entity = value;
					if ((value != null))
					{
						value.x_fav.Add(this);
						this._user_id = value.user_id;
					}
					else
					{
						this._user_id = default(Nullable<long>);
					}
					this.SendPropertyChanged("x_user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
